### PR TITLE
Fix for unquoted exe in "Open with VFS"

### PR DESCRIPTION
**Pull request by Liderate**

### CODE REVIEW

**Comment by Holt59** [comment]
This assumes that every associated program is a `.exe`, which is not the case. Aside from that, did you actually test this against the mentioned bug?

**Comment by Liderate** [comment]
I was afraid that might be the case, but yes it does make Sublime Text 4 open correctly.

**Comment by Holt59** [comment]
> I was afraid that might be the case, but yes it does make Sublime Text 4 open correctly.

Sublime Text works correctly for me even without this fix and with a space in the path. I think there is more to the issue, maybe an extra argument in the associated program. 

The proper approach here would be to look for quoted strings since if there is a space, Windows should quote it.

**Comment by AnyOldName3** [comment]
It *is* searching for quoted strings, but this is the *not quoted* path. The quotes should already have been added before control reaches this function.

**Pull request closed without merging**
