### PR TITLE
Fixed preview "file not found" error if the mod folder containing the…

### PR DESCRIPTION
**Pull request by Al12rs**
… file was on a different drive.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
Some nitpicky stuff: wouldn't make dirRelativePath More sense than direRelativePath?

**Comment by Al12rs** [comment]
but dir stands for QDir...

**Comment by Silarn** [comment]
The e bugs me but... Eh whatever. I'm not that OCD.

**Comment by SuperSandro2000** [comment]
But I am OCD

**Pull request merged**
