### PR TITLE
Don't mark a file as uninstalled when removing a backup.

### LINKED ISSUE #1059: Removal of backup marks installed file as uninstalled
## The problem:
Removal of backup marks installed file as uninstalled

## To Reproduce:
- Install a mod v1
- Install same mod v2 - replacing v1 with the backup option selected
- remove the now created backup
- see that file file used to install the mod v2 is now marked as uninstalled,

## Environment:

* Mod Organizer Version 2.2.2.1
* Desktop OS/version used to run Mod Organizer: Win 10 1909

### PR DESCRIPTION
**Pull request by Al12rs**
Fixes #1059

### CODE REVIEW

**Comment by Holt59** [comment]
I think it would be more logical to have `modUninstalled` take the `ModInfo*` as parameter and then check if the slot (`modRemoved`). This should not be a very complex change since `modUninstalled` and `modRemoved` are only used for this.

**Comment by Al12rs** [comment]
I don't really want to keep modInfos of deleted mods around and in case we need to use this in some other place it's not given that we have the modinfo available (maybe the modInfo InstallationFile needs to be updated for example).

**Comment by Holt59** [comment]
> 
> 
> I don't really want to keep modInfos of deleted mods around and in case we need to use this in some other place it's not given that we have the modinfo available (maybe the modInfo InstallationFile needs to be updated for example).

Well, I agree that keeping `modInfo`s is not that good but those are shared pointer in the first place so we could use that to avoid some issues.

In my opinion `modUninstalled` taking installation-file is not really right in the first place, or at least very specific. Same as `modRemoved` taking installation file. And not getting a `modUninstalled` signal when you remove a mod is not right either.
For this signal to make sense, we should get something usable from it, the installation file is not, except in this very specific case. 

The problem is that the `modUninstalled`/`modRemoved` signal-slot have been added for the sole purpose of marking downloaded file uninstalled, so in the current state these are mostly unusable for other purpose, but the signal name would suggest otherwise.

Either this should be fixed by making the signal more generic (e.g. by passing a `ModInfo`) or by renaming the signal / not using signal/slot for this very specific purpose.

**Comment by Al12rs** [comment]
Then I would go for renaming the signal

**Comment by Al12rs** [comment]
In any case I think it would be better to make that change after this PR is merged as the other PR also uses this signal and I don't want conflicts

**Pull request merged**
