### PR TITLE
Merge 2.3.1 changes

### PR DESCRIPTION
**Pull request by isanae**

### CODE REVIEW

**Comment by Holt59** [comment]
Why is this merge in 2_3_0?

**Comment by isanae** [comment]
Because we released 2.3.0, not 2.3, so I named it 2_3_0.

**Comment by Holt59** [comment]
Yes, but if it’s for 2.3.0 we should not merge 2.3.1 fix in it, no?

**Comment by isanae** [comment]
It's a branch for the 2.3 release.

**Pull request merged**
