### PR TITLE
Fix QTimer being created on incorrect thread after refresh.

### PR DESCRIPTION
**Pull request by Holt59**

### CODE REVIEW

**Comment by Silarn** [comment]
Interesting. I know that the signal stuff can work across threads but I'm not sure why having a lambda would trigger creating a thread.

**Comment by Holt59** [comment]
> Interesting. I know that the signal stuff can work across threads but I'm not sure why having a lambda would trigger creating a thread.

It's not 100% clear in the documentation, but with the lambda version, the context is the sender, so the functor is called in the sender context, which is a separate thread (since refresh is done in a separate thread). If you add `this`, with a lambda or a function-pointer, the context is now `this` so the call ends-up in the right thread.

**Comment by Silarn** [comment]
Yeah, that makes sense, I think.

**Review by Silarn — APPROVED** [review]

**Comment by AnyOldName3** [comment]
While this is probably the best way to fix this specific problem, if it comes up again in the future, you can be more explicit with how Qt should deal with threads when signals need wiring to slots. There are several different examples in the OMOD installer as .NET wanted to do its own things on its own threads, and Qt wasn't happy about it.

**Pull request merged**
