### PR TITLE
Add IModInterface::setUrl and remove IInstallationManager::setURL.

### PR DESCRIPTION
**Pull request by Holt59**
`uibase` PR: https://github.com/ModOrganizer2/modorganizer-uibase/pull/89

### CODE REVIEW

**Comment by AnyOldName3** [comment]
I'm thinking it might be a good idea to have this do some checking to see if it's a Nexus link and set the Nexus ID. With the number of times that the Nexus have changed their URL scheme, that's not something that's reasonable to duplicate in every plugin.

**Comment by Holt59** [comment]
> 
> 
> I'm thinking it might be a good idea to have this do some checking to see if it's a Nexus link and set the Nexus ID. With the number of times that the Nexus have changed their URL scheme, that's not something that's reasonable to duplicate in every plugin.

I thought about this but I'd rather have this in another PR. This is currently mostly used by installer using installer-specific meta-information, and you usually have both the URL and the mod ID so it's not very useful right now.

**Comment by AnyOldName3** [comment]
OMODs mostly have a Nexus URL from like five or six URL schemes ago, and don't have an explicit ID anywhere, hence wanting that feature as soon as possible. I agree that it doesn't need to be in the same PR, though.

**Comment by Silarn** [comment]
Frankly we should always prioritize data from the API. FOMODs commonly have outdated version info as well if the author forgets to update it.

**Comment by Holt59** [comment]
> OMODs mostly have a Nexus URL from like five or six URL schemes ago, and don't have an explicit ID anywhere, hence wanting that feature as soon as possible. I agree that it doesn't need to be in the same PR, though.

I didn't know that. I think the best way would be to have a separate utility function that tries to extract the ID from the URL, to avoid adding extra Nexus-specific stuff in `IModInterface`.

> 
> 
> Frankly we should always prioritize data from the API. FOMODs commonly have outdated version info as well if the author forgets to update it.

That's already the case I think. If you downloaded the file using "Download with Mod Manager" from Nexus, the Nexus ID is set automatically when calling `install()` so you can use it.

**Pull request merged**
