### PR TITLE
Add placeholder text to notification dialog

### PR DESCRIPTION
**Pull request by LostDragonist**
A lot of new users miss the fact you can click on a notification
to get more details about that notification.  This directs them
to click on stuff.

### CODE REVIEW

**Comment by Volgerd** [comment]
The program freezes as soon as you click "more" on the icon with an exclamation mark "Notification".
Trabl  -MO2 Notification

**Comment by LostDragonist** [comment]
@Volgerd If you're having an issue with the current release of MO (2.2.1), I'd suggest creating a new issue (https://github.com/ModOrganizer2/modorganizer/issues) or stopping by the discord.  If you're having an issue with the current development version of MO (2.2.2 anything), stop by the discord.

**Comment by Volgerd** [comment]
i have 2.2.1 version!

But is there already version 2.2.2?

**Comment by LostDragonist** [comment]
We're working on 2.2.2 now.  This post is about stuff in 2.2.2 which is why I was a little confused.  Please go make your own issue or stop by discord.

**Pull request merged**
