### PR TITLE
Use getName implementation of ISaveGame

### LINKED ISSUE #1430: Methods in python implementation of ISaveGame are not being called
## The problem:
The following functions are never being called by MO2:
- `getName`
- ~~`getSaveGroupIdentifier`~~
- ~~`allFiles`~~

See ModOrganizer2/modorganizer-basic_games#35 for a save game class that implements `getName`. Opening the saves tab in MO2 with that plugin will not call the implemented `getName` function.

### PR DESCRIPTION
**Pull request by erri120**
Untested quick and dirty edit on GitHub tho this should be enough... I think.

Resolves #1430

### CODE REVIEW

**Comment by Holt59** [comment]
The fix is technically ok, but it will change how saves are displayed for other games and thus some information can be lost until we add extra columns, e.g. for my FO4 it now looks like this
image

**Comment by isanae** [comment]
Do all games implement `getName()`? Should we check if it's empty and use the path if it is? Or always append the path at the end?

**Comment by Holt59** [comment]
> 
> 
> Do all games implement `getName()`? Should we check if it's empty and use the path if it is? Or always append the path at the end?

All Bethesda games have a proper `getName()` that shows something similar to my screenshot above. Basic Games `getName()` default to the filepath of the game.

**Comment by erri120** [comment]
If all Gamebryo games use GamebryoSaveGame then those are covered:
https://github.com/ModOrganizer2/modorganizer-game_gamebryo/blob/master/src/gamebryo/gamebryosavegame.cpp#L45

The BasicGameSaveGame class for the basic games have an implementation that show the filepath which can be overwritten

**Comment by isanae** [comment]
The name is much cleaner than the filename, but I don't think we should remove that information. So maybe something like `save->getName() + " (" + savesDir.relativeFilePath(save->getFilepath()) + ")"`? Or check if `getName()` contains the filename before. Or put it in the tooltip. Or something.

**Comment by erri120** [comment]
Tooltip would be the best option. If the user really wants to see the file then they will just use the _Open in Explorer_ option. I don't think it's a good idea to always put the filepath after the name: 
```c++
save->getName() + " (" + savesDir.relativeFilePath(save->getFilepath()) + ")"
```
since most games from the BasicGames plugin don't overwrite the [base implementation](https://github.com/ModOrganizer2/modorganizer-basic_games/blob/master/basic_features/basic_save_game_info.py#L23). Maybe add the filepath in the `GamebryoSaveGame` implementation of [`getName`](https://github.com/ModOrganizer2/modorganizer-game_gamebryo/blob/master/src/gamebryo/gamebryosavegame.cpp#L45)

**Comment by isanae** [comment]
I just don't think losing information is a good thing. For now, I'd check if the filename is part of what `getName()` returns. If it's not, I'd append it.

**Pull request closed without merging**
