### PR TITLE
Better blue conflict icons

### PR DESCRIPTION
**Pull request by BlueAmulet**
I remade the icons for the blue conflict icons so they had a dark outline. This make them consistent with the normal conflict icons, the error icon, and the conflict redundant icon.
I also corrected the red bar in conflict-overwritten-blue, the bar was one pixel too far down compared to conflict-overwritten.
All modified icons have been maximum compressed with 1000 iterations of zopfli and have no extraneous metadata.

### CODE REVIEW

**Comment by isanae** [comment]
Courtesy comparison:

1312-zoom
1312-dark
1312-dark-zoom

**Comment by Holt59** [comment]
Left is current, right is new?

**Review by Holt59 — APPROVED** [review]

**Comment by LostDragonist** [comment]
Would this automatically update resources.qrc or is that a manual process?  I can never remember how that works.

**Comment by Al12rs** [comment]
It's automatic, the appveyor build should end up having the icons

**Comment by Al12rs** [comment]
Works fine in the build.
@BlueAmulet Thank you very much for the contribution!

**Comment by isanae** [comment]
@BlueAmulet I'll be adding you as a contributor to the About dialog in MO. What name should I use?

**Comment by BlueAmulet** [comment]
BlueAmulet is fine

**Pull request merged**
