### PR TITLE
Starfield Updates: Shattered Space & Blueprint Support

### PR DESCRIPTION
**Pull request by Silarn**
This is a suite of updates both to support the latest Shattered Space core plugins and load order mechanics as well as adding 'blueprint flag' support to MO2.

Related PRs:
https://github.com/ModOrganizer2/modorganizer-uibase/pull/162
https://github.com/ModOrganizer2/modorganizer-esptk/pull/14
https://github.com/ModOrganizer2/modorganizer-game_starfield/pull/32
https://github.com/ModOrganizer2/modorganizer-game_gamebryo/pull/59
https://github.com/ModOrganizer2/modorganizer-plugin_python/pull/136

### CODE REVIEW

**Comment by Silarn** [comment]
Brief explanation about the sorting changes:

The blueprint flag has been in effect since the rover update to Starfield. This is currently set on the BlueprintShips-Starfield.esm. It seems to only affect master-flagged (or via extension) plugins. These plugins are forcibly moved to load after every non-blueprint plugin.

Otherwise they still follow the same basic load order rules. Core plugins > CCC plugins > plugins.txt plugins with improperly ordered masters being moved above their dependents.

**Comment by Silarn** [comment]
Addendum: A blueprint plugin set as a master to a non-blueprint plugin is largely meaningless. It may force the blueprint plugin to load earlier in the order but it will still be in the blueprint plugin grouping at the bottom of the load order. It will NOT be hoisted above a non-blueprint plugin.

**Review by Holt59 — APPROVED** [review]

**Comment by Holt59** [comment]
Merging this to move forward. At some point we might think about using some kind of enumeration and more generic stuff for all these plugin flags.

**Comment by Silarn** [comment]
> Merging this to move forward. At some point we might think about using some kind of enumeration and more generic stuff for all these plugin flags.

I want to get Starfield support out the door but my not-so-long term plan is to rip the guts out of IPluginList and implement plugin parsing and sorting in the game plugin.

That should allow us to implement BGS plugin-like mods for other games. For example, BG3 PAK files.

**Comment by Silarn** [comment]
That would include the plugin counter as well, I suppose.

**Pull request merged**
