### PR TITLE
Fix setting game path for games with executable in subfolder.

### LINKED ISSUE #1346: Incorrect game path update for game plugins with executable in subfolders
When updating the game path through the settings dialog, users have to specify the game executable and MO2 then deduce the game path from the executable.

Currently MO2 consider that the game folder is the folder containing the executable, which is not true for games for which the executable is in a sub-folder such as Darkest Dungeon from basic games.

This should be changed to take into account the actual value from `binaryName()` 

https://github.com/ModOrganizer2/modorganizer/blob/master/src/settingsdialogpaths.cpp#L100

### PR DESCRIPTION
**Pull request by Holt59**
Fixes #1346

### CODE REVIEW

**Comment by isanae** [comment]
That works fine, but I have two problems with it:

1) `update()` is called after the dialog is closed and doesn't handle failure. Either put the code in an `editingFinished` handler for the text box (which sucks because it pops a dialog), or add a new `checkValid()` member function in `SettingsTab` that's called from `SettingsDialog::exec()` and stops the process if one returns `false`.

2) The message is going to be confusing, some people will ask why you're trying to unzip the game folder. I'd say something really specific for cases where the binary name contains a directory, because it's not obvious that we're trying to find a parent folder that contains a specific path. You can also use a task dialog, put more info in the details and also log them.

**Comment by Holt59** [comment]
>     1. `update()` is called after the dialog is closed and doesn't handle failure. Either put the code in an `editingFinished` handler for the text box (which sucks because it pops a dialog), or add a new `checkValid()` member function in `SettingsTab` that's called from `SettingsDialog::exec()` and stops the process if one returns `false`.

The game path edit is read-only so I just moved the code in the "click" event, and I only update the edit if the path is valid. I'm using a member to avoid recomputing the path to save it when saving the settings.

>     2. The message is going to be confusing, some people will ask why you're trying to unzip the game folder. I'd say something really specific for cases where the binary name contains a directory, because it's not obvious that we're trying to find a parent folder that contains a specific path. You can also use a task dialog, put more info in the details and also log them.

I've changed the message, let me know what you think, I'm not really good at writing user warnings.

**Review by isanae — APPROVED** [review]

**Comment by isanae** [comment]
Can you add a short comment explaining what the `cdUp` loop is doing and why it has to do it?

**Comment by Holt59** [comment]
> 
> 
> Can you add a short comment explaining what the `cdUp` loop is doing and why it has to do it?

Done.

**Comment by isanae** [comment]
Looks good to me.

**Pull request merged**
