### PR TITLE
Allow extended selection in log list and implement copy.

### PR DESCRIPTION
**Pull request by Holt59**
What the title says.

I kept the "Copy all" menu entry, although it can now be done with Ctrl+A Ctrl+C or Ctrl+A and right-click > copy.

### CODE REVIEW

**Comment by Al12rs** [comment]
Log list you meant?

**Comment by Al12rs** [comment]
Any reason to use ContiguousSelection instead of ExtendedSelection which also allows Ctrl selection? I could see copying a couple picked out lines in the middle of a debug log

**Comment by Holt59** [comment]
> 
> 
> Any reason to use ContiguousSelection instead of ExtendedSelection which also allows Ctrl selection? I could see copying a couple picked out lines in the middle of a debug log

I thought about it but I felt like we would get tons of users copying logs on Discord with missing parts just because they felt it was not important (while it might have been). Having contiguous selection avoids having "gap" in the logs. But maybe I'm overthinking it.

**Comment by isanae** [comment]
I think having a standard selection behaviour is more important. I find it unlikely that people would do that by mistake.

**Comment by Al12rs** [comment]
Yeah I thought about that scenario as well but Shift select has the same issue with omission of data so I would just make the thing as convenient as possible for people that actually might need it.

**Review by Al12rs — APPROVED** [review]

**Pull request merged**
